### ISSUE TITLE
parseJournalEntries Convertible Submissions Can Be Duplicates

### ISSUE THREAD

**Issue by AardWolf** [m-h-c-t/mh-helper-extension#121]
Scenario: In tab 1 a user hunts with a gilded charm. The extension submits a convertible entry for each encountered gilded charm proc. If this included a trap check this could be two submission.

In tab the same user hits the horn an hour later - this tab was stale from before the trap check above. All gilded charm procs in the returned journal entries are again submitted one-by-one.

Suggestion: We include the entry_timestamp with the submission. We'll still submit them but they'll fail to be added on the backend because of a new unique constraint on hunter id, convertible id, and entry timestamp (new column).

**Comment by DevJackSmith** [comment]
if we add entry timestamp i believe we can check the entry timestamp is in the last 30 seconds, otherwise reject silently on the back end. But i guess recording timestamp is something we can do too. good catch

**Comment by AardWolf** [comment]
Could be addressed in the extension with method similar to that added for cauldron trap in #160 . Need to confirm items proc on the same timestamp; for trap checks they're different by 5 s.

**Comment by DevJackSmith** [comment]
we don't even know what setup was used on trapcheck... shouldn't we be excluding trapchecks like in our hunts collection?

**Comment by AardWolf** [comment]
For trap checks it's always been exactly 5s when I've gotten the responses. I think it's just related to how they process trap checks - it's when you do some action in-game that would trigger them then they're back-dated to the appropriate timestamp. But the other journal entries that go with it always have 5s difference.

I agree it doesn't have to be 5s always. And since we don't process trap checks anyway, the collision with the actual hunt timestamp should be infrequent enough to be ignorable.

**Comment by DevJackSmith** [comment]
added more details here: https://github.com/m-h-c-t/mh-helper-extension/issues/183

**Comment by DevJackSmith** [comment]
another idea is to use unique ids for those entries, made up of user_id and entry_id concatenated.

**Comment by DevJackSmith** [comment]
entry_timestamp was the same for both entries in my example in #183 (stale and new)

**Comment by DevJackSmith** [comment]
For proc convertibles like Gilded Charms, I believe this is mostly solved with v22.9.27 where we check pre/post entry_id before processing. That way older convertibles, don't get submitted again.
For normal convertibles i believe this is not an issues since mh doesn't allow to open same convertible twice, so response from server would be: can't open again.
Do we still want to try to add unique ids or should we close this for now?

**Comment by AardWolf** [comment]
Agreed!
