### ISSUE TITLE
Recording stale hunts sometimes

### ISSUE THREAD

**Issue by DevJackSmith** [m-h-c-t/mh-helper-extension#149]
As far as I understand our pre-hunt data is cached sometimes and makes us record stale data. (Currently using `/managers/ajax/pages/page.php`)

To avoid this we want to be able to handle all cases during our hunt (add more if I missed any):

**Possible Hunt Cases**
1. stay in same place, one hunt
2. stay in same place, stale hunts
3. move location, one hunt
4. move location, stale hunts
5. move stage, one hunt
6. move stage, stale hunts
7. move loc+stage, one hunt
8. move loc+stage, stale hunts

**Considerations**
1. Post can be out of cheese
2. Post can be out of charms
3. New location or stage in post hunt might be wrong
4. During our checking and hunting, a trap check can happen, which might screw up post hunt loc, stage, cheese, charm
5. Pre-hunt data might be cached

**Solutions**
1. Get pre-hunt data and also get num_total_turns. Post hunt (we already get the hunt response with fresh data) we can also get num_total_turns. Compare to make sure there was only 1 turn between, and record setup/environment/etc from pre-check, and outcome (mouse, loot, etc) from hunt response.

**Comment by DevJackSmith** [comment]
**Solution `#1` Details**
1. (full user object) UserInventory.getItems for location/quests/environment_atts=stage **before** hunt
as well as 
2. (very light) User.getUserData **before and after** for num_total_turns
Examples of calls:
1.
```
hg.utils.UserInventory.getItems(['whatevs'], function() {}, function (data) { console.log(data);}, true);
This is using the (second function) error response due to 'whatevs' not existing. On purpose because if the item existed, it wouldn't give us the data we want.
```
2.
```
hg.utils.User.getUserData([user.sn_user_id], ['num_total_turns','whatevs'], function(data) { console.log(data[0]);})
Fresh success response due to 'whatevs' not existing. On purpose because if the item existed, it would give us the cached data.
```

**Comment by AardWolf** [comment]
It came up on discord again: https://discord.com/channels/275500976662773761/355474934601875457/1012862195312377918

This time I proposed that since we now read the journal entries when looking for "convertibles" that aren't convertibles but are trap components we could decide not to submit hunt data if multiple hunts are returned, indicating our pre object is probably not correct.

**Comment by DevJackSmith** [comment]
this should be mostly solved with our pre check entry_id being checked against all post check entry_ids, to make sure they are all higher. Closing for now, lets reopen if not solved after we clean up db.
