### ISSUE TITLE
Tsitu's scripts don't load sometimes (due to FF bug?)

### ISSUE THREAD

**Issue by DevJackSmith** [m-h-c-t/mh-helper-extension#150]
**Workaround**
Pasting javascript code into url field manually doesn't work. We have to go to [Tsitu's page](https://tsitu.github.io/MH-Tools/cre.html), copy the bookmarklet, create a new bookmark with it, and click on the new bookmark while on mh page. Once this is done, links and autoloading in extension should work.

**Problem**
Sometimes Tsitu's files are not loaded when clicking on links or having auto-load turned on in extension. Reason for this seems unclear, but might be FF bug described here:
https://bugzilla.mozilla.org/show_bug.cgi?id=1506100

**Solution**
https://developer.chrome.com/docs/extensions/mv3/intro/mv3-migration/#executing-arbitrary-strings
Unfortunately FF doesn't support manifest v3 yet, so we'll have to do it the v2 way, and then when v3 is available in FF, switch to the v3 way.

**Comment by DevJackSmith** [comment]
Not only FF, others reported on Chrome and FF mobile

**Comment by hymccord** [comment]
I believe this was related to SHA as wel. Closing.
