### ISSUE TITLE
Update to 2021 GWH

### ISSUE THREAD

**Issue by AardWolf** [m-h-c-t/mh-helper-extension#155]
https://github.com/m-h-c-t/mh-helper-extension/blob/fc9f3712a56879f6ee2b11423881a89ef4a45880/src/scripts/main.js#L1276

**Comment by AardWolf** [comment]
Also 

`theme = theme.replace(/festive_([a-z_]+)_wrapping_paper_stat_item/i, "$1").replace(/_/g, " ");`

should be something like 

`theme = theme.replace(/festive_([a-z_]+)_yule_log_stat_item/i, "$1").replace(/_/g, " ");`

**Comment by plasmoidia** [comment]
This is in the user object:
mouse_pool:
new_year_yule_log_stat_item: 
ornament_yule_log_stat_item: 
snow_yule_log_stat_item: 
sport_yule_log_stat_item: 
toy_yule_log_stat_item:

I guess we won't know what the current_decoration: text will be exactly.

**Comment by AardWolf** [comment]
Addressed in #156
