### ISSUE TITLE
Every time Tsitu's tools update, they break in the extension

### ISSUE THREAD

**Issue by DevJackSmith** [m-h-c-t/mh-helper-extension#207]
This is because the sha on tsitus tools github branch gh-pages changes, and that sha is used to pull his files from jsdeliver cdn.

to fix this properly: we should add a flag to his tools to use local files instead of looking for sha and pulling remote files.
I started something here, but didn't finish, and recommend starting new. https://github.com/tsitu/MH-Tools/pull/99

HOWEVER as a temporary work around we can pull his sha. I strongly lean towards the actual solution instead of this temporary one, as it is against TOS to load remote code.

**Comment by DevJackSmith** [comment]
sha is stored in localstorage['tsitu-latest-sha'] and the latest one can be found here: https://api.github.com/repos/tsitu/MH-Tools/commits?sha=gh-pages

**Comment by DevJackSmith** [comment]
Might not be instant, some versions take a while to expire?

**Comment by hymccord** [comment]
Fixed in MH-Tools repo. SHA is removed.
