### ISSUE TITLE
Add Handler For Pre/Post Differences

### ISSUE THREAD

**Issue by AardWolf** [m-h-c-t/mh-helper-extension#208]
A recent change calculates the submission message for both the pre and post hunt data then compares the stages. If there is a stage mismatch the hunt is not submitted. This should be expanded to include other dimensions - location and cheese most importantly.

Doing so means we would lose some well-handled examples such as catching realm ripper.

A proposal is to add a type of pass object that can be populated like:
```
passObject = { cheese: pre_message.cheese === post_message.cheese, location: pre_message.location === post_message.location, ... }
```
This would give us binary properties that we can then clear "universally" and more specifically.

A simplified universal clearer could clear cheese (and charm) if the post cheese name is missing and the pre cheese count was 1.

A specific clearer could be something like in floating islands if the hunt count on an island was 1 then it could clear many differences based on what's in the trap library for launchpad iff the post stage is launchpad.

Specific clearers could be functionally called similar to how stage calculation and hunt detail calculations are currently done.

**Comment by AardWolf** [comment]
Marked high priority because one the structure and an example is there this becomes easy work for hacktoberfest.

**Comment by DevJackSmith** [comment]
I don't want to rush this just because hacktoberfest

**Comment by AardWolf** [comment]
but we could! I want to rush this because right now we're rejecting hunts we could be accepting.

**Comment by DevJackSmith** [comment]
we need to reject more before we accept

**Comment by DevJackSmith** [comment]
and we need to clean, to make sure we are not accepting anything bad
