### ISSUE TITLE
Default to localhost and update to mhct.win on publish

### ISSUE THREAD

**Issue by hymccord** [m-h-c-t/mh-helper-extension#229]
Using a dockerized m-h-c-t/mh-hunt-helper and running it would allow hunts to be submitted to a "real" database instead of being dumped by the official one.

Develop a way to allow that to happen with configuration files in this repo.

**Comment by DevJackSmith** [comment]
this is done by changing the main url right now to localhost in main.js. This ticket is to default to it, and only change it to prod url in the publish github action

**Comment by hymccord** [comment]
Closed via #239
