### ISSUE TITLE
Support Edge

### ISSUE THREAD

**Issue by DevJackSmith** [m-h-c-t/mh-helper-extension#44]
make the extension compatible with MS Edge

**Comment by Coding-Hen** [comment]
Seems that this might be something that is worth reavaluating bearing in mind that they are looking at releasing Chromium Edge in the newyear. Should be fairly straightforward as pretty much all Chrome addons work on Chromium Edge.

It has a little more work than Chrome but should still be quite easy.

https://docs.microsoft.com/en-us/microsoft-edge/extensions-chromium/developer-guide/port-chrome-extension
https://docs.microsoft.com/en-us/microsoft-edge/extensions-chromium/publish/publish-extension

**Comment by DevJackSmith** [comment]
Edge is now based on Chromium and some people already installed our extension on it. So this is supported (unoficially).
